### ISSUE TITLE
Why is JQuery included?

### ISSUE THREAD

**Issue by justin-mclaren** [gatsbymanor/gatsby-theme-massively#2]
I hate to add JQuery onto a site that's already built on React and Gatsby. Why is it included? Just for the scrolling effect or am I gonna break something else if I delete it?

**Comment by nodox** [comment]
No go ahead and delete it. You can delete the `js` folder as well. PR's are welcome to make the theme more stable. The goal of the `js` folder was to serve as a guide to recreate all the animations that are in the original massively theme on html5up.net. If you feel up to the challenge please give it a shot.
